# Generated by Django 4.2.7 on 2023-12-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_course_created_at_alter_lesson_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='project_upload_link',
        ),
    ]
