# Generated by Django 4.2.7 on 2023-12-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_lesson_project_upload_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
    ]
