# Generated by Django 4.2.7 on 2023-12-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celuser',
            old_name='gr_num',
            new_name='gr_number',
        ),
        migrations.AlterField(
            model_name='courseattempt',
            name='status',
            field=models.CharField(choices=[], default='started', max_length=64),
        ),
        migrations.AlterField(
            model_name='lessonattempt',
            name='status',
            field=models.CharField(choices=[], max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='celuser',
            unique_together={('school', 'gr_number')},
        ),
    ]
