# Generated by Django 4.2.7 on 2023-12-27 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonattempt',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonattempt',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('finished', 'finished')], default='started', max_length=64),
        ),
        migrations.AddField(
            model_name='lessonattempt',
            name='sync_device_id',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonattempt',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
