# Generated by Django 4.2.7 on 2023-12-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseattempt',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='lessonattempt',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='finished_at',
        ),
        migrations.AddField(
            model_name='courseattempt',
            name='sync_device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lessonattempt',
            name='sync_device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='sync_device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courseattempt',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lessonattempt',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
