# Generated by Django 4.2.7 on 2023-12-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_alter_celuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonattempt',
            name='project_upload_link',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
