# Generated by Django 4.2.7 on 2023-12-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_lessonattempt_project_upload_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseattempt',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('finished', 'finished')], max_length=64),
        ),
        migrations.AlterField(
            model_name='lessonattempt',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('finished', 'finished')], max_length=64),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('finished', 'finished')], max_length=64),
        ),
    ]
